[package]
name = "rustack"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = "4.5.40"
clap_derive = "4.5.40"
colored = "3.0.0"
derive = "1.0.0"
dialoguer = "0.11.0"
serde = { version = "1.0.219", features = ["derive"] }
tera = "1.20.0"
rstack-macros = { workspace = true }
quote = "1.0.40"
